# Generated by Django 4.0.2 on 2022-03-14 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_profile_follower_profile_follower_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('follower', 'following')},
        ),
    ]
