# Generated by Django 4.0.2 on 2022-04-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_follower_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post', 'user')},
        ),
    ]
