# Generated by Django 4.0.2 on 2022-04-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_profile_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set(),
        ),
    ]
