# Generated by Django 4.0.2 on 2022-04-12 05:28

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_remove_profile_follower_profile_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name=network.models.User),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following',
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name=network.models.User),
        ),
    ]
