# Generated by Django 4.0.2 on 2022-04-17 05:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='total_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
