# Generated by Django 4.0.2 on 2022-04-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='total_likes', to='network.Likes'),
        ),
    ]
