# Generated by Django 4.0.2 on 2022-04-17 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
